import type { Metadata } from "next";
import "./globals.css";
import { plusJakartaSans } from "./fonts";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body
        className={`${plusJakartaSans.className} antialiased bg-linear-to-b from-cyan-50 from-0% to-indigo-50 to-100%`}
      > <Navbar />
        {children}
        <Footer />
      </body>

    </html>
  );
}
